const SERVICE_IDENTIFIER = {
  UserService: Symbol.for("IUserService"),
  UserRepository: Symbol.for("IUserRepository"),
  AdminService: Symbol.for("IAdminService"),
  AdminRepository: Symbol.for("IAdminRepository"),
  BdoService: Symbol.for("IBdoService"),
  BdoRepository: Symbol.for("IBdoRepository"),
  BranchService: Symbol.for("IBranchService"),
  BranchRepository: Symbol.for("IBranchRepository"),
  CheckinService: Symbol.for("ICheckinService"),
  CheckinRepository: Symbol.for("ICheckinRepository"),
  FinanceRepository: Symbol.for("IFinanceRepository"),
  FinanceService: Symbol.for("IFinanceService"),
  BookingService: Symbol.for("IBookingService"),
  BookingRepository: Symbol.for("IBookingRepository"),
  SlotRepository: Symbol.for("ISlotRepository"),
  SlotService: Symbol.for("ISlotService"),
  VendorRepository: Symbol.for("IVendorRepository"),
  MasterRepository: Symbol.for("IMasterRepository"),
  AppointmentRepository: Symbol.for("IAppointmentRepository"),
  AppointmentService: Symbol.for("IAppointmentService"),
  SubServiceRepository: Symbol.for("ISubServiceRepository"),
  VehicleRepository: Symbol.for("IVehicleRepository"),
  VehicleService: Symbol.for("IVehicleService"),
  RegionRepository: Symbol.for("IRegionRepository"),
  RegionService: Symbol.for("IRegionService"),
  LabService: Symbol.for("ILabService"),
  VendorService: Symbol.for("IVendorService"),
  LabRepository: Symbol.for("ILabRepository"),
  ZoneRepository: Symbol.for("IZoneRepository"),
  ZoneService: Symbol.for("IZoneService"),
  StaffMemberRepository: Symbol.for("IStaffMemberRepository"),
  StaffMemberService: Symbol.for("IStaffMemberService"),
  NotificationRepository: Symbol.for("INotificationRepository"),
  UnitOfWork: Symbol.for("IUnitOfWork"),
  ServiceRepository: Symbol.for("IServiceRepository"),
  SubServiceService: Symbol.for("ISubServiceService"),
};

export default SERVICE_IDENTIFIER;
