enum COMMISSION_TYPE {
    PERCENTAGE = 'PERCENTAGE',
    FIXED = 'FIXED'
}

enum SUB_SERVICE_TYPE {
    URGENT = 'URGENT',
    NORMAL = 'NORMAL'
}

export {
    COMMISSION_TYPE,
    SUB_SERVICE_TYPE
}