enum TYPE {
    NORMAL = "NORMAL",
    COVID_TEST = "COVID_TEST",
    COVID_VACINATION = 'COVID_VACINATION',
    DOCTOR_APPOINTMENT = 'DOCTOR_APPOINTMENT'
}

enum COMMISSION_TYPE {
    PERCENTAGE = 'PERCENTAGE',
    FIXED = 'FIXED'
}

enum TEST_SERVICE_TYPE {
    URGENT = 'URGENT',
    NORMAL = 'NORMAL',
    HOME_SAMPLE = 'HOME_SAMPLE',
    WALK_IN = 'WALK_IN'
}

enum TEST_BRANCH_NAME {
    SHABAZ = 'shabaz',
    LOCAL_BRANCH = 'shahbaz'
}


export {
    TYPE,
    TEST_SERVICE_TYPE,
    COMMISSION_TYPE,
    TEST_BRANCH_NAME,
}