const StaticStringKeys = {
  INVALID_REQUEST: 'Invalid request',
  INVALID_CREDENTIAL: 'Invalid credential',
  INVALID_ACCESS_TOKEN: 'Invalid access token',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  INVALID_EMAIL: 'Invalid email',
  INVALID_PASSWORD: 'Invalid password',
  INVALID_USERNAME: 'Invalid username',
  USER_NOT_FOUND: 'User not found',
  USERNAME_NOT_AVAILABLE: 'Try another username',
  EMAIL_NOT_AVAILABLE: 'Try another email',
  UNKNOWN_ERROR_TRY_AGAIN: 'Unknown error occured. Please try again.',
  REPOSITORY_ERROR_INVALID_ID: 'Invalid id',
  FAILED_TO_SAVE: 'Failed to save document',
  FAILED_TO_UPDATE: 'Failed to update',
  FAILED_TO_DELETE: 'Failed to delete',
  SUCCESSFULL_SAVE: 'Data added successfully',
  SUCCESSFULL_UPDATE: 'successfully updated',
  EMAIL_IS_ALREADY_REGISTER: 'Email is already registered',
  LOGIN_FAILED: 'Your email or password do not match',
  ACCOUNT_BLOCKED: 'Your account is blocked',
  OTP_CODE_SEND_LOGIN: 'code are sent in your email',
  VERIFICATION_NOT_FOUND: 'Verification is not available',
  VERIFICATION_FAILED: 'The Code You entered Is incorrect',
  SUCCESSFULL_LOGIN: 'Login are successfully',
  SUPER_ADMIN_RESTRICTED: 'Super admin cannot be updated',
  NOT_INITIAL_BOOKING_ERROR: 'You are not a part of the initial booking So Can I Create New Appointment',
  SELECT_PAYMENT_METHOD: 'Please Select payment Method',
  APPOINTMENT_ASSIGN_SUCCESSFUL: 'Appointment assign to user Successfully',
  ASSIGN_MEMBER: "Team members Assigned",
  CANNOT_CHANGE_PRICE: "Cannot change price after user registered in Appointment",
  CANNOT_CHANGE_PAYMENT: "Cannot change payment type after user registered in Appointment",
  BOOKING_IS_FAILED_TO_UPDATED: "Booking is failed to update beacuse sample are collected all appointments",
  BOOKING_CANCELLED : "Booking Successfully Canceled",
  DATA_MISSED : "Data not provided",
  USER_NOT_REGISTER: "User is not registered",
  _UPDATE_SUCCESSFUL:(model:string)=> `${model} updated successfully`,
  NOT_FOUND: (model: any) => `${model} is not found`,
  CREATED_SUCCESSFUL: (model: any) => `${model} created successfully`,
  DELETED_SUCCESSFUL: (model: any) => `${model} deleted successfully`,
  INVALID_ID: (model: any) => `Invalid ${model} Id`,

}

export default StaticStringKeys;
